### ISSUE TITLE
chi-router doesnt seem to work well with swaggerui

### ISSUE THREAD

**Issue by talbSE** [flowchartsman/swaggerui#2]
### Issue
it looks like when using swaggerui with go-chi router module, the http request fails to find the embedded CSS files and resources.

<img width="773" alt="Screen Shot 2022-01-31 at 9 47 25" src="https://user-images.githubusercontent.com/80450892/151756323-e42a182a-8b83-4f14-886f-019b0ed4a268.png">

### Snippet
```
import github.com/go-chi/chi
r := chi.NewRouter()
r.Handle("/swagger/", http.StripPrefix("/swagger", swaggerui.Handler(spec)))
```

### Additional Info
go 1.17
github.com/go-chi/chi/v5 v5.0.7

**Comment by meximonster** [comment]
Hello, the same issue occurs when using gorilla/mux

**Comment by Goxiaoy** [comment]
@meximonster 
```
router := mux.NewRouter()
router.PathPrefix("/swagger").Handler(http.StripPrefix("/swagger", swaggerui.Handler(spec)))
```
Works for me

**Comment by scohen-examity** [comment]
Same issue here with go-chi -- would love to use this

**Comment by luukkemp** [comment]
This works for me:

`router.Mount("/swagger", http.StripPrefix("/swagger", swaggerui.Handler(spec)))`

**Comment by flowchartsman** [comment]
So do we have a good solution here, should I close this issue?

**Comment by scohen-examity** [comment]
yes

**Comment by itaranto** [comment]
I'm having the same issue with `gin-gonic`.

I tried the following:

```go
router.GET("/swagger/", gin.WrapH(http.StripPrefix("/swagger", swaggerui.Handler(spec))))
```

`router` is a `gin.Engine` instance.

**Comment by itaranto** [comment]
> I'm having the same issue with `gin-gonic`.
> 
> I tried the following:
> 
> router.GET("/swagger/", gin.WrapH(http.StripPrefix("/swagger", swaggerui.Handler(spec))))
> 
> `router` is a `gin.Engine` instance.

I was able to fix it by using wildcards:

```go
router.GET("/swagger/*any", gin.WrapH(http.StripPrefix("/swagger", swaggerui.Handler(spec))))
```
